default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: admin
  port: 5432

development:
  <<: *default
  database: greetings
  host: localhost
  username: postgres
  password: admin
  port: 5432

test:
  <<: *default
  database: greetings_test
  host: localhost
  username: postgres
  password: admin
  port: 5432

production:
  <<: *default
  database: greetings
  username: postgres
  password: admin
